#!/bin/bash
# bootstrap-buildenv - clone and initialise an opendreambox BuildEnv variant.
#
# Usage:
#   bootstrap-buildenv <fork> <branch>
#
#     fork:   dreamlegacy      -> https://github.com/dreamlegacy/opendreambox
#             opendreambox     -> https://github.com/WXbet/opendreambox
#     branch: pyro | krogoth | ...  (any branch of the chosen fork)
#
# Result layout under $HOME (which is the host bind-mount, so all this
# persists across container restarts):
#
#   $HOME/
#   |-- sources/                                (shared DL_DIR pool)
#   |-- dreamlegacy/
#   |   |-- pyro/                               (checkout)
#   |   |   `-- sources -> ../../sources        (symlink)
#   |   `-- krogoth/ ...
#   `-- opendreambox/
#       |-- pyro/
#       |   `-- sources -> ../../sources
#       `-- krogoth/ ...
#
# Idempotent:
#   * clone                -> skipped if .git already present
#   * make update          -> skipped if .bootstrap-done marker present
#   * sources symlink      -> recreated only if missing or pointing elsewhere
#   * conf/local-ext.conf  -> WRITTEN ONLY IF ABSENT; existing configs are left alone
#                             (this is the opendreambox convention: `make init`
#                             auto-includes it into every per-machine local.conf)
set -euo pipefail

fork="${1:-}"
branch="${2:-}"

if [ -z "$fork" ] || [ -z "$branch" ]; then
    cat >&2 <<USAGE
Usage: bootstrap-buildenv <fork> <branch>

  fork:   dreamlegacy | opendreambox
  branch: any git branch of the chosen fork (e.g. pyro, krogoth)

Examples:
  bootstrap-buildenv opendreambox krogoth
  bootstrap-buildenv dreamlegacy pyro
USAGE
    exit 1
fi

case "$fork" in
    dreamlegacy)
        url="https://github.com/dreamlegacy/opendreambox.git"
        ;;
    opendreambox|wxbet)
        url="https://github.com/WXbet/opendreambox.git"
        fork="opendreambox"
        ;;
    *)
        echo "Unknown fork '$fork'. Use 'dreamlegacy' or 'opendreambox'." >&2
        exit 1
        ;;
esac

target="$HOME/$fork/$branch"

# Central sources pool -- shared across every BuildEnv checkout.
mkdir -p "$HOME/sources"

# --- 1. clone ---------------------------------------------------------
if [ ! -d "$target/.git" ]; then
    echo ">>> Cloning $url ($branch) into $target"
    mkdir -p "$(dirname "$target")"
    git clone -b "$branch" "$url" "$target"
else
    echo ">>> $target already checked out, skipping clone"
fi

cd "$target"

# --- 2. make update (initialises submodules + BuildEnv config) --------
if [ ! -f .bootstrap-done ]; then
    echo ">>> Running 'make update' (submodules + BuildEnv init)"
    make update
    touch .bootstrap-done
else
    echo ">>> .bootstrap-done marker present, skipping 'make update'"
fi

# --- 3. sources symlink to the shared pool ---------------------------
if [ ! -L sources ] || [ "$(readlink sources)" != "../../sources" ]; then
    echo ">>> (Re)creating sources -> ../../sources"
    rm -rf sources
    ln -s ../../sources sources
fi

# --- 4. local-ext.conf: only create if absent -------------------------
# opendreambox's `MACHINE=xxx make init` builds a per-machine local.conf
# under build/<MACHINE>/conf/ that auto-includes ../../conf/local-ext.conf
# for user-added settings. That's the ONLY file we edit; the per-machine
# local.conf is auto-generated and must never be hand-edited.
mkdir -p conf
if [ ! -f conf/local-ext.conf ]; then
    echo ">>> Writing conf/local-ext.conf (defaults from legacy builder)"
    cat > conf/local-ext.conf <<'LOCALEXT'
# Generated by bootstrap-buildenv. Not touched on re-run.
# Edit freely below -- your changes survive re-runs of bootstrap-buildenv.


# ================== SOURCES ==================

# Consult the in-image snapshot of upstream sources before hitting the
# network. Anything missing is fetched over the network and lands in
# DL_DIR (opendreambox points DL_DIR at ../sources -- symlinked to the
# shared /home/builder/sources pool on the host bind-mount).
PREMIRRORS ?= "\
    bzr://.*/.*     file:///opt/dl-mirror/ \n \
    cvs://.*/.*     file:///opt/dl-mirror/ \n \
    git://.*/.*     file:///opt/dl-mirror/ \n \
    gitsm://.*/.*   file:///opt/dl-mirror/ \n \
    hg://.*/.*      file:///opt/dl-mirror/ \n \
    osc://.*/.*     file:///opt/dl-mirror/ \n \
    p4://.*/.*      file:///opt/dl-mirror/ \n \
    svn://.*/.*     file:///opt/dl-mirror/ \n \
    ftp://.*/.*     file:///opt/dl-mirror/ \n \
    http://.*/.*    file:///opt/dl-mirror/ \n \
    https://.*/.*   file:///opt/dl-mirror/ \n \
"

# Personal online mirror -- prepended to the standard MIRRORS list.
# MIRRORS is consulted when PREMIRRORS + upstream SRC_URI both fail.
MIRRORS =+ "https://.*/.*  https://dreambox.dedyn.io/sources/ \n"


# ================== OSCAM ==================

OSCAMNAME = "oscam-master"
OSCAMCONF = "${sysconfdir}/tuxbox/config"
OSCAMPORT = "8888"


# ================== PACKAGE FEED ==================

# The "2.6" is the opendreambox distro version. If you build a BuildEnv
# whose distro is a different release, edit this line accordingly.
DISTRO_FEED_URI = "https://dreamboxupdate.com/opendreambox/2.6/unstable/${PR}/${MACHINE}"


# ================== PACKAGE SIGNING ==================

# All commented out by default. Only some opendreambox forks (e.g. WXbet)
# carry the "package_manager: sign DEB package feeds" patch on
# openembedded-core that implements DEB package signing. Vanilla /
# dreamlegacy don't -- and even PACKAGE_FEED_SIGN='0' isn't enough
# because PACKAGE_CLASSES pulling in sign_package_feed.bbclass triggers
# other paths that assume signing infrastructure exists.
#
# To enable (only if your fork supports it): uncomment ALL lines below,
# adjust PACKAGE_FEED_GPG_NAME to your key's fingerprint, and place the
# keyring at host ~/dreamos-builds/.gnupg/ (which appears as
# /home/builder/.gnupg/ inside the container thanks to the bind-mount)
# plus a plain-text passphrase file (chmod 0600).
#
#PACKAGE_FEED_SIGN = '1'
#PACKAGE_CLASSES = "package_deb sign_package_feed"
#PACKAGE_FEED_GPG_BACKEND = 'local'
#PACKAGE_FEED_GPG_SIGNATURE_TYPE = 'BIN'
#PACKAGE_FEED_GPG_NAME = "11C6F48B5290A9850EE7D61D7C374EAD72A9AED9"
#PACKAGE_FEED_GPG_PASSPHRASE_FILE = "/home/builder/.gnupg/passphrase"


# ================== MEMORY / PARALLELISM CAPS ==================

# Commented out by default -- opendreambox auto-detects nproc and sets
# BB_NUMBER_THREADS + PARALLEL_MAKE aggressively. That's fine on a real
# build server (32+ GB RAM) but OOM-kills cc1plus on constrained hosts
# like a stock WSL2 instance (6-8 GB RAM). Symptoms:
#     internal compiler error: Killed (program cc1plus)
# on template-heavy recipes -- most commonly boost::log and qtwebkit.
#
# Two levers:
#   BB_NUMBER_THREADS = how many recipes bitbake compiles in parallel
#   PARALLEL_MAKE     = -j inside each recipe's make invocation
# Worst-case peak = BB_NUMBER_THREADS x PARALLEL_MAKE cc1plus instances,
# each ~500 MB to 2 GB during heavy template work.
#
# Rule of thumb by host RAM:
#   ~8 GB   :  BB_NUMBER_THREADS = "3",  PARALLEL_MAKE = "-j 4"
#   ~16 GB  :  BB_NUMBER_THREADS = "6",  PARALLEL_MAKE = "-j 6"
#   ~32 GB  :  no caps needed (auto-detected values are fine)
#
# Per-recipe overrides (targeted, only for the known hogs) are usually
# enough if the global auto-detected values are within reason for your
# host. The BB_NUMBER_THREADS / PARALLEL_MAKE globals are the escape
# hatch when even per-recipe caps aren't sufficient.

# --- global caps (uncomment on constrained hosts) ---
#BB_NUMBER_THREADS = "3"
#PARALLEL_MAKE     = "-j 4"

# --- per-recipe caps (targeted, safe to leave on even with plenty of RAM) ---
#PARALLEL_MAKE_pn-boost           = "-j 4"
#PARALLEL_MAKE_pn-boost-native    = "-j 4"
#PARALLEL_MAKE_pn-qtwebkit        = "-j 4"
#PARALLEL_MAKE_pn-qtwebkit-native = "-j 4"
LOCALEXT
else
    echo ">>> conf/local-ext.conf already exists, leaving untouched"
fi

cat <<DONE

>>> Ready at $target
    cd $target
    # source the BuildEnv environment as documented by its README/Makefile
    # (typically: source bitbake.env  OR  make setup-env)

DONE
