#!/bin/bash
# bootstrap-buildenv - clone and initialise an opendreambox BuildEnv variant.
#
# Usage:
#   bootstrap-buildenv <fork> <branch>
#
#     fork:   dreamlegacy      -> https://github.com/dreamlegacy/opendreambox
#             opendreambox     -> https://github.com/WXbet/opendreambox
#     branch: pyro | krogoth | ...  (any branch of the chosen fork)
#
# Result layout under $HOME (which is the host bind-mount, so all this
# persists across container restarts):
#
#   $HOME/
#   |-- sources/                                (shared DL_DIR pool)
#   |-- dreamlegacy/
#   |   |-- pyro/                               (checkout)
#   |   |   `-- sources -> ../../sources        (symlink)
#   |   `-- krogoth/ ...
#   `-- opendreambox/
#       |-- pyro/
#       |   `-- sources -> ../../sources
#       `-- krogoth/ ...
#
# Idempotent:
#   * clone                -> skipped if .git already present
#   * make update          -> skipped if .bootstrap-done marker present
#   * sources symlink      -> recreated only if missing or pointing elsewhere
#   * conf/local-ext.conf  -> WRITTEN ONLY IF ABSENT; existing configs are left alone
#                             (this is the opendreambox convention: `make init`
#                             auto-includes it into every per-machine local.conf)
set -euo pipefail

fork="${1:-}"
branch="${2:-}"

if [ -z "$fork" ] || [ -z "$branch" ]; then
    cat >&2 <<USAGE
Usage: bootstrap-buildenv <fork> <branch>

  fork:   dreamlegacy | opendreambox
  branch: any git branch of the chosen fork (e.g. pyro, krogoth)

Examples:
  bootstrap-buildenv opendreambox krogoth
  bootstrap-buildenv dreamlegacy pyro
USAGE
    exit 1
fi

case "$fork" in
    dreamlegacy)
        url="https://github.com/dreamlegacy/opendreambox.git"
        ;;
    opendreambox|wxbet)
        url="https://github.com/WXbet/opendreambox.git"
        fork="opendreambox"
        ;;
    *)
        echo "Unknown fork '$fork'. Use 'dreamlegacy' or 'opendreambox'." >&2
        exit 1
        ;;
esac

target="$HOME/$fork/$branch"

# Central sources pool -- shared across every BuildEnv checkout.
mkdir -p "$HOME/sources"

# --- 1. clone ---------------------------------------------------------
if [ ! -d "$target/.git" ]; then
    echo ">>> Cloning $url ($branch) into $target"
    mkdir -p "$(dirname "$target")"
    git clone -b "$branch" "$url" "$target"
else
    echo ">>> $target already checked out, skipping clone"
fi

cd "$target"

# --- 2. make update (initialises submodules + BuildEnv config) --------
if [ ! -f .bootstrap-done ]; then
    echo ">>> Running 'make update' (submodules + BuildEnv init)"
    make update
    touch .bootstrap-done
else
    echo ">>> .bootstrap-done marker present, skipping 'make update'"
fi

# --- 3. sources symlink to the shared pool ---------------------------
if [ ! -L sources ] || [ "$(readlink sources)" != "../../sources" ]; then
    echo ">>> (Re)creating sources -> ../../sources"
    rm -rf sources
    ln -s ../../sources sources
fi

# --- 4. local-ext.conf: only create if absent -------------------------
# opendreambox's `MACHINE=xxx make init` builds a per-machine local.conf
# under build/<MACHINE>/conf/ that auto-includes ../../conf/local-ext.conf
# for user-added settings. That's the ONLY file we edit; the per-machine
# local.conf is auto-generated and must never be hand-edited.
mkdir -p conf
if [ ! -f conf/local-ext.conf ]; then
    echo ">>> Writing conf/local-ext.conf (defaults from legacy builder)"
    cat > conf/local-ext.conf <<'LOCALEXT'
# Generated by bootstrap-buildenv. Not touched on re-run.
# Edit freely below -- your changes survive re-runs of bootstrap-buildenv.


# ================== SOURCES ==================

# Consult the in-image snapshot of upstream sources before hitting the
# network. Anything missing is fetched over the network and lands in
# DL_DIR (opendreambox points DL_DIR at ../sources -- symlinked to the
# shared /home/builder/sources pool on the host bind-mount).
PREMIRRORS ?= "\
    bzr://.*/.*     file:///opt/dl-mirror/ \n \
    cvs://.*/.*     file:///opt/dl-mirror/ \n \
    git://.*/.*     file:///opt/dl-mirror/ \n \
    gitsm://.*/.*   file:///opt/dl-mirror/ \n \
    hg://.*/.*      file:///opt/dl-mirror/ \n \
    osc://.*/.*     file:///opt/dl-mirror/ \n \
    p4://.*/.*      file:///opt/dl-mirror/ \n \
    svn://.*/.*     file:///opt/dl-mirror/ \n \
    ftp://.*/.*     file:///opt/dl-mirror/ \n \
    http://.*/.*    file:///opt/dl-mirror/ \n \
    https://.*/.*   file:///opt/dl-mirror/ \n \
"

# Personal online mirror -- prepended to the standard MIRRORS list.
# MIRRORS is consulted when PREMIRRORS + upstream SRC_URI both fail.
MIRRORS =+ "https://.*/.*  https://dreambox.dedyn.io/sources/ \n"


# ================== OSCAM ==================

OSCAMNAME = "oscam-master"
OSCAMCONF = "${sysconfdir}/tuxbox/config"
OSCAMPORT = "8888"


# ================== PACKAGE FEED ==================

# The "2.6" is the opendreambox distro version. If you build a BuildEnv
# whose distro is a different release, edit this line accordingly.
DISTRO_FEED_URI = "https://dreamboxupdate.com/opendreambox/2.6/unstable/${PR}/${MACHINE}"


# ================== PACKAGE SIGNING ==================

# Package signing needs a GPG keyring + passphrase file INSIDE the
# container at ~/.gnupg/. Since $HOME is bind-mounted from the host's
# ~/dreamos-builds/, place your key material at:
#     host: ~/dreamos-builds/.gnupg/
#     host: ~/dreamos-builds/.gnupg/passphrase   (plain text, mode 0600)
# and it appears as /home/builder/.gnupg/ inside the container.
#
# If you don't have a signing key set up yet, comment out this whole
# block or the package-signing task will fail.
PACKAGE_FEED_SIGN = '1'
PACKAGE_CLASSES = "package_deb sign_package_feed"
PACKAGE_FEED_GPG_BACKEND = 'local'
PACKAGE_FEED_GPG_SIGNATURE_TYPE = 'BIN'
PACKAGE_FEED_GPG_NAME = "11C6F48B5290A9850EE7D61D7C374EAD72A9AED9"
PACKAGE_FEED_GPG_PASSPHRASE_FILE = "/home/builder/.gnupg/passphrase"
LOCALEXT
else
    echo ">>> conf/local-ext.conf already exists, leaving untouched"
fi

cat <<DONE

>>> Ready at $target
    cd $target
    # source the BuildEnv environment as documented by its README/Makefile
    # (typically: source bitbake.env  OR  make setup-env)

DONE
